### ISSUE TITLE
object attribute goes missing in record when it's re-published

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-backend#210] opened 2020-08-27 22:51 UTC
1
https://specialcollections.du.edu/object/073e319f-e8fb-4ecd-8b32-b3033aa1d7be#?c=&m=&s=&cv= and objects in the lillian covillo collection were reindexed and republished because their abstracts were originally not displaying. suspect that this causes the object path to disappear once it gets republished

what kristen did: i unpublished the whole of the mable rilling collection and then republished it so now it is show up, i will do the same with the Lillian Covillo papers

2
also make script for objects to find the missing object path, it's possible that in the past any other objects that were republished also are missing the object path

**Comment by freyesdulib** [comment] 2020-09-02 22:08
Issue is caused by the automated metadata updates.  I have a process running to fix all broken display records.

**Comment by freyesdulib** [comment] 2020-11-03 19:58
Batch update process modified to update non-compound object records.  Compound object bug fix in progress.

**Comment by freyesdulib** [comment] 2020-11-16 22:25
A fix is in place.  The updates will be monitored over the next few weeks to confirm that the process is working as expected.

**Comment by freyesdulib** [comment] 2021-03-26 20:00
Fix completed.

**Closed by freyesdulib** 2021-03-26 20:00 UTC
Labels: bug
